apiVersion: v1
kind: Service
metadata:
  name: phi4-service
  namespace: phi4-inference
  labels:
    app: phi4
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: webui
    port: 7860
    targetPort: 7860
    protocol: TCP
  selector:
    app: phi4
---
apiVersion: v1
kind: Service
metadata:
  name: phi4-api-service
  namespace: phi4-inference  
  labels:
    app: phi4
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: phi4
---
apiVersion: v1
kind: Service
metadata:
  name: phi4-webui-service
  namespace: phi4-inference
  labels:
    app: phi4
spec:
  type: ClusterIP
  ports:
  - name: webui
    port: 7860
    targetPort: 7860
    protocol: TCP
  selector:
    app: phi4
